version: 2
jobs:
  build-site:
    docker:
      - image: circleci/golang:1.11
      
    working_directory: ~/kaiif.net
    steps:
      - checkout
      - run: go get github.com/gohugoio/hugo
      - run: hugo
      - persist_to_workspace:
          root: ~/kaiif.net
          paths: 
            - public
            - Dockerfile
  build-push-docker:
    docker:
      - image: docker:17.05.0-ce-git
    working_directory: ~/kaiif.net
    steps:
      - setup_remote_docker
      - attach_workspace:
          at: ~/kaiif.net
      - run: export IMAGE_ID=$(docker build .)
      - run: docker login -u _json_key -p "$(echo $DOCKER_PUSH_GCLOUD_SA_JSON | base64 -d)" https://gcr.io
      - run: docker tag $IMAGE_ID gcr.io/$GCLOUD_PROJECT_ID/kaiif
      - run: docker push gcr.io/$GCLOUD_PROJECT_ID/kaiif

workflows:
  version: 2

  btd:
    jobs:
      - build-site
      - build-push-docker:
          requires:
            - build-site
