version: 2
jobs:
  build-site:
    docker:
      - image: circleci/golang:1.11
      
    working_directory: ~/kaiif.net
    steps:
      - checkout
      - run: go get github.com/gohugoio/hugo
      - run: hugo
      - persist_to_workspace:
          root: ~/kaiif.net
          paths: 
            - public
            - Dockerfile
  build-docker:
    docker:
      - image: docker:17.05.0-ce-git
    working_directory: ~/kaiif.net
    steps:
      - setup_remote_docker
      - attach_workspace:
          at: ~/kaiif.net
      - run: docker build .

workflows:
  version: 2

  btd:
    jobs:
      - build-site
      - build-docker:
          requires:
            - build-site
